// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {llm} from '../models';
import {main} from '../models';

export function AddProvider(arg1:llm.Provider):Promise<void>;

export function DetectLanguage(arg1:string):Promise<main.DetectLanguageResponse>;

export function GetActiveProvider():Promise<llm.Provider>;

export function GetDefaultLanguages():Promise<Record<string, string>>;

export function GetProviders():Promise<Array<llm.Provider>>;

export function RemoveProvider(arg1:string):Promise<void>;

export function SetDefaultLanguage(arg1:string,arg2:string):Promise<void>;

export function SetProviderActive(arg1:string):Promise<void>;

export function TranslateWithLLM(arg1:main.TranslateRequest):Promise<string>;

export function UpdateProvider(arg1:string,arg2:llm.Provider):Promise<void>;
