// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProvider(arg1) {
  return window['go']['main']['App']['AddProvider'](arg1);
}

export function GetActiveProvider() {
  return window['go']['main']['App']['GetActiveProvider']();
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function RemoveProvider(arg1) {
  return window['go']['main']['App']['RemoveProvider'](arg1);
}

export function SetProviderActive(arg1) {
  return window['go']['main']['App']['SetProviderActive'](arg1);
}

export function TranslateWithLLM(arg1) {
  return window['go']['main']['App']['TranslateWithLLM'](arg1);
}
