// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function AddProvider(arg1:types.Provider):Promise<void>;

export function DetectLanguage(arg1:string):Promise<types.DetectResult>;

export function GetAccessibilityPermission():Promise<boolean>;

export function GetActiveProvider():Promise<types.Provider>;

export function GetDefaultLanguages():Promise<Record<string, string>>;

export function GetProviders():Promise<Array<types.Provider>>;

export function RemoveProvider(arg1:string):Promise<void>;

export function SetDefaultLanguage(arg1:string,arg2:string):Promise<void>;

export function SetProviderActive(arg1:string):Promise<void>;

export function TakeScreenshotAndOCR():Promise<string>;

export function ToggleWindowVisibility():Promise<void>;

export function TranslateWithLLM(arg1:types.TranslateRequest):Promise<types.TranslateResult>;

export function UpdateProvider(arg1:string,arg2:types.Provider):Promise<void>;
